import type {
  AuditLogEntry,
  EmergencyCard,
  FamilyMember,
  MedicalRecord,
  Medicine,
  Reminder,
  StorageStat,
} from "./types";

/**
 * In-memory demo dataset. When Supabase/Prisma env vars are configured the API
 * layer swaps this out for the real database. Until then the whole app runs on
 * this data so it can be explored end-to-end with zero setup.
 */

export const familyMembers: FamilyMember[] = [
  {
    id: "m1",
    name: "Aarav Sharma",
    relationship: "Self",
    dateOfBirth: "1990-04-12",
    gender: "Male",
    bloodGroup: "O+",
    photoUrl:
      "https://images.unsplash.com/photo-1633332755192-727a05c4013d?w=256&q=80&auto=format&fit=crop",
    conditions: ["Type 2 Diabetes", "Hypertension"],
    allergies: ["Penicillin"],
    emergencyContactName: "Priya Sharma",
    emergencyContactPhone: "+91 98765 43210",
    heightCm: 178,
    weightKg: 82,
    createdAt: "2024-01-04T10:00:00Z",
  },
  {
    id: "m2",
    name: "Priya Sharma",
    relationship: "Spouse",
    dateOfBirth: "1992-09-23",
    gender: "Female",
    bloodGroup: "B+",
    photoUrl:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=256&q=80&auto=format&fit=crop",
    conditions: ["Hypothyroidism"],
    allergies: ["Sulfa drugs"],
    emergencyContactName: "Aarav Sharma",
    emergencyContactPhone: "+91 98765 43211",
    heightCm: 163,
    weightKg: 58,
    createdAt: "2024-01-05T10:00:00Z",
  },
  {
    id: "m3",
    name: "Ananya Sharma",
    relationship: "Daughter",
    dateOfBirth: "2016-06-15",
    gender: "Female",
    bloodGroup: "O+",
    photoUrl:
      "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=256&q=80&auto=format&fit=crop",
    conditions: ["Asthma"],
    allergies: ["Peanuts", "Dust mites"],
    emergencyContactName: "Priya Sharma",
    emergencyContactPhone: "+91 98765 43210",
    heightCm: 128,
    weightKg: 26,
    createdAt: "2024-01-06T10:00:00Z",
  },
  {
    id: "m4",
    name: "Ramesh Sharma",
    relationship: "Father",
    dateOfBirth: "1958-02-02",
    gender: "Male",
    bloodGroup: "A+",
    photoUrl:
      "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=256&q=80&auto=format&fit=crop",
    conditions: ["Coronary Artery Disease", "Arthritis"],
    allergies: [],
    emergencyContactName: "Aarav Sharma",
    emergencyContactPhone: "+91 98765 43211",
    heightCm: 170,
    weightKg: 74,
    createdAt: "2024-01-07T10:00:00Z",
  },
];

export const medicalRecords: MedicalRecord[] = [
  {
    id: "r1",
    memberId: "m1",
    title: "HbA1c Blood Test",
    category: "Report",
    date: "2025-06-10",
    doctorName: "Dr. Neha Kapoor",
    hospital: "Apollo Hospital",
    diagnosis: "Type 2 Diabetes - controlled",
    medicines: ["Metformin 500mg"],
    tags: ["diabetes", "blood test", "2025"],
    fileType: "pdf",
    createdAt: "2025-06-10T09:00:00Z",
  },
  {
    id: "r2",
    memberId: "m1",
    title: "Lipid Profile",
    category: "Report",
    date: "2025-03-22",
    doctorName: "Dr. Neha Kapoor",
    hospital: "Apollo Hospital",
    diagnosis: "Borderline high cholesterol",
    tags: ["cholesterol", "blood test", "2025"],
    fileType: "pdf",
    createdAt: "2025-03-22T09:00:00Z",
  },
  {
    id: "r3",
    memberId: "m1",
    title: "Chest X-Ray",
    category: "Scan",
    date: "2024-11-05",
    doctorName: "Dr. Vikram Rao",
    hospital: "Fortis Healthcare",
    diagnosis: "Normal study",
    tags: ["x-ray", "chest", "2024"],
    fileType: "image",
    createdAt: "2024-11-05T09:00:00Z",
  },
  {
    id: "r4",
    memberId: "m1",
    title: "Cardiology Consultation",
    category: "Visit",
    date: "2024-09-14",
    doctorName: "Dr. Sunil Mehta",
    hospital: "Fortis Healthcare",
    diagnosis: "Hypertension - stage 1",
    medicines: ["Amlodipine 5mg"],
    tags: ["cardiology", "bp", "2024"],
    createdAt: "2024-09-14T09:00:00Z",
  },
  {
    id: "r5",
    memberId: "m2",
    title: "Thyroid Function Test",
    category: "Report",
    date: "2025-05-02",
    doctorName: "Dr. Reena Joshi",
    hospital: "Max Healthcare",
    diagnosis: "Hypothyroidism - on treatment",
    medicines: ["Thyronorm 50mcg"],
    tags: ["thyroid", "2025"],
    fileType: "pdf",
    createdAt: "2025-05-02T09:00:00Z",
  },
  {
    id: "r6",
    memberId: "m3",
    title: "Pediatric Asthma Review",
    category: "Visit",
    date: "2025-04-18",
    doctorName: "Dr. Alok Nair",
    hospital: "Rainbow Children's Hospital",
    diagnosis: "Mild persistent asthma",
    medicines: ["Budesonide inhaler"],
    tags: ["asthma", "pediatric", "2025"],
    createdAt: "2025-04-18T09:00:00Z",
  },
  {
    id: "r7",
    memberId: "m3",
    title: "MMR Vaccination",
    category: "Vaccination",
    date: "2024-06-15",
    hospital: "Rainbow Children's Hospital",
    tags: ["vaccine", "mmr", "2024"],
    createdAt: "2024-06-15T09:00:00Z",
  },
  {
    id: "r8",
    memberId: "m4",
    title: "Coronary Angiography",
    category: "Scan",
    date: "2025-01-30",
    doctorName: "Dr. Sunil Mehta",
    hospital: "Fortis Healthcare",
    diagnosis: "70% blockage LAD",
    tags: ["cardiac", "angiography", "2025"],
    fileType: "image",
    createdAt: "2025-01-30T09:00:00Z",
  },
  {
    id: "r9",
    memberId: "m4",
    title: "Pharmacy Bill - Cardiac Meds",
    category: "Bill",
    date: "2025-02-05",
    hospital: "Apollo Pharmacy",
    notes: "₹2,340 - monthly cardiac medication",
    tags: ["bill", "pharmacy", "2025"],
    fileType: "image",
    createdAt: "2025-02-05T09:00:00Z",
  },
];

export const medicines: Medicine[] = [
  {
    id: "med1",
    memberId: "m1",
    name: "Metformin",
    dosage: "500mg",
    schedule: ["morning", "night"],
    startDate: "2024-01-10",
    reminderEnabled: true,
    notes: "Take after meals",
    expiryDate: "2026-08-01",
    createdAt: "2024-01-10T09:00:00Z",
  },
  {
    id: "med2",
    memberId: "m1",
    name: "Amlodipine",
    dosage: "5mg",
    schedule: ["morning"],
    startDate: "2024-09-14",
    reminderEnabled: true,
    expiryDate: "2026-03-01",
    createdAt: "2024-09-14T09:00:00Z",
  },
  {
    id: "med3",
    memberId: "m2",
    name: "Thyronorm",
    dosage: "50mcg",
    schedule: ["morning"],
    startDate: "2024-03-01",
    reminderEnabled: true,
    notes: "Empty stomach, 30 min before breakfast",
    expiryDate: "2025-09-01",
    createdAt: "2024-03-01T09:00:00Z",
  },
  {
    id: "med4",
    memberId: "m3",
    name: "Budesonide Inhaler",
    dosage: "200mcg",
    schedule: ["morning", "night"],
    startDate: "2025-04-18",
    reminderEnabled: false,
    expiryDate: "2026-01-01",
    createdAt: "2025-04-18T09:00:00Z",
  },
  {
    id: "med5",
    memberId: "m4",
    name: "Atorvastatin",
    dosage: "20mg",
    schedule: ["night"],
    startDate: "2025-01-30",
    reminderEnabled: true,
    expiryDate: "2024-12-01",
    createdAt: "2025-01-30T09:00:00Z",
  },
];

const now = new Date();
const inHours = (h: number) =>
  new Date(now.getTime() + h * 3600 * 1000).toISOString();
const inDays = (d: number) =>
  new Date(now.getTime() + d * 24 * 3600 * 1000).toISOString();

export const reminders: Reminder[] = [
  {
    id: "rem1",
    memberId: "m1",
    type: "Medicine",
    title: "Metformin 500mg",
    dateTime: inHours(3),
    channels: ["push", "email"],
    completed: false,
    createdAt: now.toISOString(),
  },
  {
    id: "rem2",
    memberId: "m1",
    type: "Appointment",
    title: "Endocrinologist follow-up",
    dateTime: inDays(2),
    notes: "Apollo Hospital, Dr. Neha Kapoor",
    channels: ["push"],
    completed: false,
    createdAt: now.toISOString(),
  },
  {
    id: "rem3",
    memberId: "m3",
    type: "Vaccination",
    title: "Influenza booster",
    dateTime: inDays(9),
    channels: ["email"],
    completed: false,
    createdAt: now.toISOString(),
  },
  {
    id: "rem4",
    memberId: "m4",
    type: "Lab Test",
    title: "Fasting lipid profile",
    dateTime: inDays(5),
    channels: ["push", "email"],
    completed: false,
    createdAt: now.toISOString(),
  },
  {
    id: "rem5",
    memberId: "m2",
    type: "Medicine",
    title: "Thyronorm 50mcg",
    dateTime: inHours(14),
    channels: ["push"],
    completed: true,
    createdAt: now.toISOString(),
  },
];

export const emergencyCards: EmergencyCard[] = familyMembers.map((m) => ({
  memberId: m.id,
  bloodGroup: m.bloodGroup,
  allergies: m.allergies,
  conditions: m.conditions,
  currentMedicines: medicines
    .filter((med) => med.memberId === m.id)
    .map((med) => `${med.name} ${med.dosage}`),
  emergencyContactName: m.emergencyContactName,
  emergencyContactPhone: m.emergencyContactPhone,
  organDonor: m.id === "m1",
}));

export const auditLogs: AuditLogEntry[] = [
  {
    id: "a1",
    action: "Report uploaded",
    target: "HbA1c Blood Test",
    actor: "aarav@medvault.ai",
    timestamp: inHours(-2),
    ip: "103.21.44.12",
  },
  {
    id: "a2",
    action: "Emergency card shared",
    target: "Ramesh Sharma",
    actor: "aarav@medvault.ai",
    timestamp: inHours(-26),
    ip: "103.21.44.12",
  },
  {
    id: "a3",
    action: "Login",
    target: "Web session",
    actor: "aarav@medvault.ai",
    timestamp: inHours(-30),
    ip: "103.21.44.12",
  },
  {
    id: "a4",
    action: "Member added",
    target: "Ananya Sharma",
    actor: "aarav@medvault.ai",
    timestamp: inDays(-6),
    ip: "103.21.44.12",
  },
];

export const storageStat: StorageStat = {
  usedMb: 428,
  totalMb: 2048,
};
